### ISSUE TITLE
Add clapfn

### ISSUE THREAD

**Issue by oliversandli** [xflywind/awesome-nim#11]
I realize that this is my own project, but would you consider adding `clapfn`? I wrote it to be as simple for the end user as possible, but still have all the features expected from a command line argument parser.

Also, no hard feelings if you don't think it is worthy! Just wanted to let you know about it. Happy programming!

Nimble link: [clapfn](https://nimble.directory/pkg/clapfn)

GitHub link: [clapfn](https://github.com/oliversandli/clapfn)

**Comment by xflywind** [comment]
Hi, PR is welcome!

**Comment by oliversandli** [comment]
Ok, thanks!
