### ISSUE TITLE
Mailing list archive URL

### ISSUE THREAD

**Issue by wavexx** [xflywind/awesome-nim#28]
I was searching for some pointers, when I stumbled on the "community" section.
The "mailing list archive" URL:

https://github.com/xflywind/awesome-nim/blob/4b1dcb947271f4e417db2f1233ad7ca78b44df84/README.md?plain=1#L526

points to the old archive, which is no longer updated in favor of the forum. However there is now a forum->mailing list archive available here:

https://www.mail-archive.com/nim-general@lists.nim-lang.org/info.html
https://www.mail-archive.com/nim-general@lists.nim-lang.org/

The archive is also accessible via NNTP at news.gmane.io, group ``comp.lang.nim.general`` for those old folks that still use gmane. Both are read-only, however I find them more convenient to follow.

I'm not sure how I would add those links, but I thought at least the current mailing list archive is more relevant than the dead one.

**Comment by xflywind** [comment]
Sorry for the confusion.

> but I thought at least the current mailing list archive is more relevant than the dead one.

I agree and feel free to make a PR.
